image: buildstream/testsuite-debian:9-5da27168-32c47d1c

cache:
  key: "$CI_JOB_NAME-"
  paths:
    - cache/

stages:
  - test
  - post

variables:
  PYTEST_ADDOPTS: "--color=yes"
  INTEGRATION_CACHE: "${CI_PROJECT_DIR}/cache/integration-cache"
  COVERAGE_PREFIX: "${CI_JOB_NAME}."


#####################################################
#                    Test stage                     #
#####################################################

# Run premerge commits
#
.tests-template: &tests
  stage: test

  before_script:
  # Diagnostics
  - mount
  - df -h

  # Remove MANIFEST.in
  - rm MANIFEST.in

  script:
  - useradd -Um buildstream
  - chown -R buildstream:buildstream .

  # Run the tests as a simple user to test for permission issues
  - su buildstream -c "${TEST_COMMAND}"

  after_script:
  except:
  - schedules
  artifacts:
    paths:
    - .coverage-reports

normal-tests:
  <<: *tests

  variables:
    TEST_COMMAND: "tox -- --color=yes --integration"

skip-sdist:
  <<: *tests

  variables:
    TEST_COMMAND: "tox --develop -- --color=yes --integration"
