[pytest]
addopts = --verbose --basetemp ./tmp --pep8 --cov=buildstream --cov-config .coveragerc
norecursedirs = integration-tests*
python_files = tests/*/*.py
pep8maxlinelength = 119
pep8ignore =
    * E129
    * E125
    doc/source/conf.py ALL
    tmp/* ALL
    */lib/python3* ALL
    */bin/* ALL
    buildstream/_fuse/fuse.py ALL
    .eggs/* ALL
env =
    D:BST_TEST_SUITE=True
